### ISSUE TITLE
pip install django-chatterbot not working

### ISSUE THREAD

**Issue by soumendrak** [gunthercox/django_chatterbot#6]
In Python ver 2.7 the above command is not working.
[PyPi](https://pypi.python.org/pypi?%3Aaction=search&term=django-chatterbot&submit=search) does not have any package under this name too.

**Comment by gunthercox** [comment]
It appears I never uploaded this package to PYPI. If you download the code you can install it locally by running `pip install ./django_chatterbot/`.

**Comment by anksv** [comment]
After downloading the code and running the command:

vagrant@precise32:~/django/django_chatterbot$ pip install ./django_chatterbot/
Directory './django_chatterbot/' is not installable. File 'setup.py' not found.

**Comment by anksv** [comment]
i copied the setup.py inside the folder django_chatterbot and ran again

**Comment by anksv** [comment]
vagrant@precise32:~/django/django_chatterbot$ sudo pip install ./django_chatterbot/
Unpacking ./django_chatterbot
  Running setup.py (path:/tmp/pip-_xWF2t-build/setup.py) egg_info for package from file:///home/vagrant/django/django_chatterbot/django_chatterbot
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-_xWF2t-build/setup.py", line 4, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'README.rst')) as readme:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-_xWF2t-build/README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-_xWF2t-build/setup.py", line 4, in <module>

    with open(os.path.join(os.path.dirname(__file__), 'README.rst')) as readme:

IOError: [Errno 2] No such file or directory: '/tmp/pip-_xWF2t-build/README.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-_xWF2t-build
Storing debug log for failure in /home/vagrant/.pip/pip.log

**Comment by gunthercox** [comment]
Support for integrating ChatterBot with Django has been added as a core part of the chatterbot package. Installing an additional package will not be needed. See https://github.com/gunthercox/ChatterBot/pull/266 for details on these changes that will be available in the next release of ChatterBot.
