### ISSUE TITLE
MongoDB as backend?

### ISSUE THREAD

**Issue by aaronhmiller** [gunthercox/django_chatterbot#8]
Wondering if you've advice on getting Chatterbot's Django Example working against MongoDB? I've gotten the terminal adapter to work with Mongo. Seems like it should be possible with Django as well, just not sure how.

**Comment by gunthercox** [comment]
You may want to look into a Django database backend for Mongo DB. There is a package called _Django Mongo Engine_ which looks fairly straightforward to setup and use (http://django-mongodb-engine.readthedocs.io/en/latest/topics/setup.html). I haven't used Mongo DB with django before but there is a good change that it will "just work" if you set your project up with Django Mongo Engine.

**Comment by aaronhmiller** [comment]
Thanks
